#!/bin/bash

### BEGIN INIT INFO
# Provides:          AutoRemoteTerminal
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# Create a shell script that loads application on boot of the system

# sudo cp AutoRemoteTerminal /etc/init.d/
# sudo chmod +x AutoRemoteTerminal 
# sudo chmod +x /etc/init.d/AutoRemoteTerminal 
# sudo update-rc.d AutoRemoteTerminal defaults


# Run on boot

sudo RTS <key> <Port> <Max Clients>


exit 0
